# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'p3.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(750, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 711, 321))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.piano = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.piano.setObjectName("piano")
        self.verticalLayout_3.addWidget(self.piano)
        self.guitar = QtWidgets.QRadioButton(self.horizontalLayoutWidget)
        self.guitar.setObjectName("guitar")
        self.verticalLayout_3.addWidget(self.guitar)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalFrame_2 = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.horizontalFrame_2.setObjectName("horizontalFrame_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.horizontalFrame_2)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 30, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.csharp = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.csharp.sizePolicy().hasHeightForWidth())
        self.csharp.setSizePolicy(sizePolicy)
        self.csharp.setMinimumSize(QtCore.QSize(0, 0))
        self.csharp.setMaximumSize(QtCore.QSize(60, 16777215))
        self.csharp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.csharp.setObjectName("csharp")
        self.horizontalLayout_2.addWidget(self.csharp)
        self.eflat = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.eflat.sizePolicy().hasHeightForWidth())
        self.eflat.setSizePolicy(sizePolicy)
        self.eflat.setMinimumSize(QtCore.QSize(0, 0))
        self.eflat.setMaximumSize(QtCore.QSize(60, 16777215))
        self.eflat.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.eflat.setObjectName("eflat")
        self.horizontalLayout_2.addWidget(self.eflat)
        spacerItem1 = QtWidgets.QSpacerItem(80, 10, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.fsharp = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.fsharp.sizePolicy().hasHeightForWidth())
        self.fsharp.setSizePolicy(sizePolicy)
        self.fsharp.setMinimumSize(QtCore.QSize(0, 0))
        self.fsharp.setMaximumSize(QtCore.QSize(60, 16777215))
        self.fsharp.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.fsharp.setObjectName("fsharp")
        self.horizontalLayout_2.addWidget(self.fsharp)
        self.aflat = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.aflat.sizePolicy().hasHeightForWidth())
        self.aflat.setSizePolicy(sizePolicy)
        self.aflat.setMinimumSize(QtCore.QSize(0, 0))
        self.aflat.setMaximumSize(QtCore.QSize(60, 16777215))
        self.aflat.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.aflat.setObjectName("aflat")
        self.horizontalLayout_2.addWidget(self.aflat)
        self.bflat = QtWidgets.QPushButton(self.horizontalFrame_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bflat.sizePolicy().hasHeightForWidth())
        self.bflat.setSizePolicy(sizePolicy)
        self.bflat.setMinimumSize(QtCore.QSize(0, 0))
        self.bflat.setMaximumSize(QtCore.QSize(60, 16777215))
        self.bflat.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"color: rgb(255, 255, 255);\n"
"background-color: rgb(0, 0, 0);")
        self.bflat.setObjectName("bflat")
        self.horizontalLayout_2.addWidget(self.bflat)
        spacerItem2 = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.verticalLayout.addWidget(self.horizontalFrame_2)
        self.horizontalFrame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.horizontalFrame.setObjectName("horizontalFrame")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.horizontalFrame)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.c_note = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.c_note.sizePolicy().hasHeightForWidth())
        self.c_note.setSizePolicy(sizePolicy)
        self.c_note.setMinimumSize(QtCore.QSize(0, 0))
        self.c_note.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.c_note.setObjectName("c_note")
        self.horizontalLayout.addWidget(self.c_note)
        self.d_note = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.d_note.sizePolicy().hasHeightForWidth())
        self.d_note.setSizePolicy(sizePolicy)
        self.d_note.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.d_note.setObjectName("d_note")
        self.horizontalLayout.addWidget(self.d_note)
        self.e_note = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.e_note.sizePolicy().hasHeightForWidth())
        self.e_note.setSizePolicy(sizePolicy)
        self.e_note.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.e_note.setObjectName("e_note")
        self.horizontalLayout.addWidget(self.e_note)
        self.f_note = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.f_note.sizePolicy().hasHeightForWidth())
        self.f_note.setSizePolicy(sizePolicy)
        self.f_note.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.f_note.setObjectName("f_note")
        self.horizontalLayout.addWidget(self.f_note)
        self.g_note = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.g_note.sizePolicy().hasHeightForWidth())
        self.g_note.setSizePolicy(sizePolicy)
        self.g_note.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.g_note.setObjectName("g_note")
        self.horizontalLayout.addWidget(self.g_note)
        self.a_note = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.a_note.sizePolicy().hasHeightForWidth())
        self.a_note.setSizePolicy(sizePolicy)
        self.a_note.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.a_note.setObjectName("a_note")
        self.horizontalLayout.addWidget(self.a_note)
        self.b_note = QtWidgets.QPushButton(self.horizontalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.b_note.sizePolicy().hasHeightForWidth())
        self.b_note.setSizePolicy(sizePolicy)
        self.b_note.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.b_note.setObjectName("b_note")
        self.horizontalLayout.addWidget(self.b_note)
        self.verticalLayout.addWidget(self.horizontalFrame)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 750, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.piano.setText(_translate("MainWindow", "Piano"))
        self.guitar.setText(_translate("MainWindow", "guitar"))
        self.csharp.setText(_translate("MainWindow", "C#"))
        self.eflat.setText(_translate("MainWindow", "Eb"))
        self.fsharp.setText(_translate("MainWindow", "F#"))
        self.aflat.setText(_translate("MainWindow", "Ab"))
        self.bflat.setText(_translate("MainWindow", "Bb"))
        self.c_note.setText(_translate("MainWindow", "C"))
        self.d_note.setText(_translate("MainWindow", "D"))
        self.e_note.setText(_translate("MainWindow", "E"))
        self.f_note.setText(_translate("MainWindow", "F"))
        self.g_note.setText(_translate("MainWindow", "G"))
        self.a_note.setText(_translate("MainWindow", "A"))
        self.b_note.setText(_translate("MainWindow", "B"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
